name: MundoSK
author: Tlatoani
description: World Borders, World Management, Books, Enchanted Books, Sockets, and optional TerrainControl hook for Skript!
version: 1.6.3
main: com.pie.tlatoani.Mundo
depend: [Skript]
soft-depend: [TerrainControl, ProtocolLib, SkQuery]